  spring:
    application:
      name: Names
    datasource:
      url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASS}
    jpa:
      open-in-view: true
      properties:
        hibernate:
          ddl-auto: update

